on:
  push:
    branches:
      - ci
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
#      - uses: actions/checkout@v3
      - name: Find circuits
#        if: false
        run: |
          set -e
          set -x
          urls=("https://iden3-circuits-bucket.s3.eu-west-1.amazonaws.com/branch/ci.zip" "https://iden3-circuits-bucket.s3.eu-west-1.amazonaws.com/ci.zip" "http://google.com")
          for url in "${urls[@]}"; do
            echo "do loop for $url"
            output=$(curl -sI "$url")
            status_code=$(echo "$output" | grep -o 'HTTP/[0-9].[0-9] [0-9]*' | awk '{print $2}')
            echo "status code: ${status_code}"
            if [ "$status_code" -eq 200 ]; then
              echo "found $url"
              export CIRCUITS_URL=$url
              export CIRCUITS_FILE="${CIRCUITS_URL##*/}"
              echo "CIRCUITS_URL=${CIRCUITS_URL}" >> $GITHUB_ENV
              echo "CIRCUITS_FILE=${CIRCUITS_FILE}" >> $GITHUB_ENV
          
              etag=$(echo "$output" | grep -i 'ETag:' | awk -F': ' '{print $2}' | tr -d '\n\r"')
              if [ -n "$etag" ]; then
                echo "CIRCUITS_ETAG=$etag" >> $GITHUB_ENV
              fi
              
              break
            fi
          done

#      - name: temp values
#        run: |
#          echo "CIRCUITS_URL=${CIRCUITS_URL}}" >> $GITHUB_ENV
#          echo "CIRCUITS_FILE=${CIRCUITS_FILE}}" >> $GITHUB_ENV

      - name: Restore circuits from cache if ETag is present
        id: circuits-restore
        if: env.CIRCUITS_ETAG != ''
        uses: actions/cache/restore@v3
        with:
          path: circuits
          key: ${{ env.CIRCUITS_FILE }}-${{ env.CIRCUITS_ETAG }}-2

      - name: Show circuits url
        run: echo '[2] circuits url -${{ env.CIRCUITS_URL }}- | -${{ env.CIRCUITS_ETAG }}-'

      - name: Download circuits if cache missed
        id: circuits-download
        if: steps.circuits-restore.outputs.cache-hit != 'true'
        run: |
          set -e
          mkdir circuits
          cd circuits
          curl -D ${{ env.CIRCUITS_FILE }}.headers -o ${{ env.CIRCUITS_FILE }} ${{ env.CIRCUITS_URL }}
          unzip ${{ env.CIRCUITS_FILE }}
          etag=$(grep -i 'ETag:' < "${{ env.CIRCUITS_FILE }}.headers" | awk -F': ' '{print $2}' | tr -d '\n\r"')
          if [ -n "$etag" ]; then
            echo "CIRCUITS_ETAG=$etag" >> $GITHUB_ENV
          fi

      - name: Show circuits url
        run: |
          echo "[3] circuits url -${{ env.CIRCUITS_URL }}- | -${{ env.CIRCUITS_ETAG }}-"
          echo "[4] ${{ steps.circuits-download.outcome }}"

      - name: Save circuits to cache if ETag is present
        if: env.CIRCUITS_ETAG != '' && steps.circuits-download.outcome == 'success'
        uses: actions/cache/save@v3
        with:
          path: circuits
          key: ${{ env.CIRCUITS_FILE }}-${{ env.CIRCUITS_ETAG }}-2
