on:
  push:
    branches:
      - ci
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
#      - uses: actions/checkout@v3
      - name: Find circuits
        run: |
          set -e
          set -x
          mkdir circuits
          urls=("https://iden3-circuits-bucket.s3.eu-west-1.amazonaws.com/branch/ci.zip" "https://iden3-circuits-bucket.s3.eu-west-1.amazonaws.com/ci.zip" "http://google.com")
          for url in "${urls[@]}"; do
            echo "do loop for $url"
            output=$(curl -sI "$url")
            status_code=$(echo "$output" | grep -o 'HTTP/[0-9].[0-9] [0-9]*' | awk '{print $2}')
            echo "status code: ${status_code}"
            if [ "$status_code" -eq 200 ]; then
              echo "found $url"
              break
            fi
          done
