on:
  push:
    branches:
      - ci
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
#      - uses: actions/checkout@v3
      - run: |
          set -e
          mkdir circuits
          urls=("https://iden3-circuits-bucket.s3.eu-west-1.amazonaws.com/branch/ci.zip", "https://iden3-circuits-bucket.s3.eu-west-1.amazonaws.com/ci.zip")
          for url in "${urls[@]}"; do
            echo $url
          done
