on:
  push:
    branches:
      - job_control
  pull_request:

jobs:
  jc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: .github/scripts/run.sh
      continue-on-error: true
      id: run-jc
    - run: |
        echo "Job Control: ${{ steps.run-jc.outcome }}"
    - run: cat newman-error.out
    - run: cat newman-ok.out