on:
  push:
    branches:
      - job_control
  pull_request:

jobs:
  jc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: .github/scripts/run.sh
      continue-on-error: true
      id: run-jc
    - run: cat newman-error.out
    - run: cat newman-ok.out
    - run: exit 1
      if: steps.run-jc.outcome != 'success'
