on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.20.2-bullseye
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo github.event_name ${{ github.event_name }}
          echo github.event.action ${{ github.event.action }}
          echo github.event.pull_request.merged ${{ github.event.pull_request.merged }}
          go test ./..
